# Generated by Django 3.2.6 on 2021-09-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Address'),
        ),
    ]
