# Generated by Django 3.2.6 on 2021-09-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210902_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='address_user', to='accounts.Address'),
        ),
    ]
