# Generated by Django 3.2.6 on 2021-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210902_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Address'),
        ),
    ]
